routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/
// Route::group(['prefix' => 'admin', 'middleware' => ['role:admin']], function() {
//     Route::get('/', 'AdminController@welcome');
//     Route::get('/manage', ['middleware' => ['permission:manage-admins'], 'uses' => 'AdminController@manageAdmins']);
// });
// Route::prefix('admin')->group(function(){
// 	Route::get('login', 'Admin\LoginController@showLoginForm')->name('admin.login');
//     Route::post('login', 'Admin\LoginController@login');
//     Route::post('logout', 'Admin\LoginController@logout')->name('admin.logout');

//         // Registration Routes...
//     Route::get('register', 'Admin\RegisterController@showRegistrationForm')->name('admin.register');
//     Route::post('register', 'Admin\RegisterController@register');

//         // Password Reset Routes...
//     Route::get('password/reset','Admin\ForgotPasswordController@showLinkRequestForm')->name('admin.password.request');
//     Route::post('password/email', 'Admin\ForgotPasswordController@sendResetLinkEmail')->name('admin.password.email');
//     Route::get('password/reset/{token}', 'Admin\ResetPasswordController@showResetForm')->name('admin.password.reset');
//     Route::post('password/reset', 'Admin\ResetPasswordController@reset');

//     Route::get('/','Admin\AdminController@index')->name('admin.home');
// });
Route::prefix('users')->middleware('web')->group(function(){
	// Auth::routes();
	//login
	Route::get('/login', ['as'=>'login','uses'=>'User\LoginController@showLoginForm']);
	Route::post('/login', ['as'=>'login','uses'=>'User\LoginController@processLogin']);
	//logout
	Route::post('/logout', ['as'=>'logout','uses'=>'User\LoginController@logout']);
	//register
	Route::get('/register', ['as'=>'register','uses'=>'User\RegisterController@showRegisterForm']);
	Route::post('/register', ['as'=>'register','uses'=>'User\RegisterController@processRegister']);
	//Password maintain
	Route::get('password/reset','User\ForgotPasswordController@showLinkRequestForm')->name('password.request');
    Route::post('password/email', 'User\ForgotPasswordController@sendResetLinkEmail')->name('password.email');
    Route::get('password/reset/{token}', 'User\ResetPasswordController@showResetForm')->name('password.reset');
    Route::post('password/reset', 'User\ResetPasswordController@reset');

});
Route::resource('users','UsersController');
Route::resource('posts','PostsController', ['except' => 'show'])->middleware('auth');
Route::prefix('posts')->middleware('auth')->group(function(){
	Route::resource('/{post}/comments','CommentsController');
    Route::get('/category/{slug}','PostsController@showPostByCategory')->name('posts.category');
    Route::get('/{slug}/{id}','PostsController@show')->name('posts.show');
    Route::post('/{type}','PostsController@SortedPost')->name('posts.sort');
});

// Route::get('home',['as'=>'home', 'uses'=>'MyController@home']);



//Route::get('view/', ['as'=>'view','uses'=>'UsersController@index']);



// Route::get('/dtus1', function(){
//     $faker = Faker\Factory::create();
//     $limit = 100;
//     $posts = [];
//     for ($i = 0; $i < $limit; $i++) {
//     	$title = $faker->text(200);
//     	$slug = str_slug($title, '-');
//         $posts[$i] = [
//             'id'            => $faker->numberBetween(1,100),
//             'title'			=>$title,
//             'content'       =>$faker->paragraph,
//             'slug'			=>$slug,
//             'rate'			=>$faker->numberBetween($min = 0, $max = 100),
//             'active'		=>true,
//             'id_user'       => $faker->numberBetween(1,100),
//             'id_category'	=>$faker->numberBetween(1,100),
//         ];
//     }
//     return response()->json($posts);
// });


Route::get('/','HomeController@home')->name('layouts.home');

// Route::get("/dtus", function()
// {
//     $post = Post::where('id',1)->get();
//     foreach($post as $p)
//         echo $p->created_at;
//  //    dd($dt);
// 	// return view('Post');
// });

Route::get('/home', 'HomeController@home')->name('home');
// Route::get('/app', 'HomeController@index')->name('home');

resources/views/home.blade.php
@extends('layouts.main')

@section('sidebar')
  
  <!-- Blog Entries Column -->
  <div class="col-md-8">
    <div class="d-flex justify-content-between">
      <h1>@yield('title','Home Page')</h1>
      
      @section('sorting')
        @include('layouts.sorting')
      @show
    </div>
    <hr>
  @section('content')
      @include('layouts.errors')
      @foreach($post as $key => $value)
          <!-- Blog Post -->
          <div class="card mb-4" id="accordion">
            <img class="card-img-top" data-toggle="modal" data-target="#exampleModal" src="http://placehold.it/750x300" alt="Card image cap">
            <div class="modal fade" id="exampleModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
              <div class="modal-dialog modal-lg" role="document">
                <div class="modal-content">
                  <div class="modal-body justify-content-center">
                    <img src="http://placehold.it/750x300" alt="Card image cap">
                  </div>
                  <div class="modal-footer">
                    <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
                  </div>
                </div>
              </div>
            </div>
            <div class="card-header" id="heading{{$value->id}}">
              <a data-toggle="collapse" data-target="#collapse{{$value->id}}" aria-expanded="true" aria-controls="collapseOne" href="#"><h2>{{$value->title}}</h2>
              </a>
            </div>
            <div class="card-body" id="collapse{{$value->id}}" class="collapse show" aria-labelledby="heading{{$value->id}}" data-parent="#accordion">
              <p>{!!str_limit($value->content, $limit = 200, $end = '...')!!}</p>
              
              <a href="{{route('posts.show',['slug'=>str_slug($value->title,'-'),'id'=>$value->id])}}" class="btn btn-primary">
              Read More &rarr;</a>
              
            </div>
            <div class="card-footer text-muted">
              Posted on {{$value->created_at}} by
              <a href="{{route('users.show',['id'=>$value->users->id])}}">{{$value->users->name}}</a>
            </div>
          </div>
      @endforeach
    @show
    </div>
      <!-- Sidebar Widgets Column -->
        <div class="col-md-4">

          <!-- Search Widget -->
          <div class="card my-4">
            <h5 class="card-header">Search</h5>
            <div class="card-body">
              <div class="input-group">
                <input type="text" class="form-control" placeholder="Search for...">
                <span class="input-group-btn">
                  <button class="btn btn-secondary" type="button">Go!</button>
                </span>
              </div>
            </div>
          </div>

          <!-- Categories Widget -->
          <div class="card my-4">
            <h5 class="card-header">Categories</h5>
            <div class="card-body">
              <div class="row">
                <div class="container">
                <div class="col">
                  <ul class="list-unstyled mb-0">
                    @foreach($category as $key => $value)
                    <li>
                      <a href="{{route('posts.category',['slug'=>$value->slug])}}">{{$value->category_name}}</a>
                    </li>
                    @endforeach
                  </ul>
                </div>
              </div>
              </div>
            </div>
          </div>

          <!-- Side Widget -->
          <div class="card my-4">
            <h5 class="card-header">Side Widget</h5>
            <div class="card-body">
            
                <a class="btn btn-primary" href="{{route('posts.create')}}">New Post</a>
              
            </div>
          </div>

        </div>
  <script type="text/javascript">
    $('.dropdown-toggle').dropdown()
  </script>
@endsection

resources/views/login.blade.php
@extends('layouts.main')


@section('sidebar')
<div class="container main">
    <div class="row justify-content-center">
        <div class="col-md-7">
          <div class="card">
            <div class="card-header bg-dark box-shadow text-light"><strong><i>User Login</i></strong></div>
            <div class="card-body">
              <form method="POST" action="{{ route('login') }}">
                      @csrf
                        @include('layouts.errors')
                        <div class="form-group row ">
                            <label for="email" class="col-sm-4 col-form-label text-md-right">E-Mail Address</label>

                            <div class="col-md-6">
                                <input id="email" type="email" class="form-control{{ $errors->has('email') ? ' is-invalid' : '' }}" name="email" value="{{ old('email') }}" required autofocus>
                            </div>
                        </div>

                        <div class="form-group row">
                            <label for="password" class="col-md-4 col-form-label text-md-right">Password</label>

                            <div class="col-md-6">
                                <input id="password" type="password" class="form-control{{ $errors->has('password') ? ' is-invalid' : '' }}" name="password" required>

                            </div>
                        </div>

                        <div class="form-group row">
                            <div class="col-md-6 offset-md-4">
                                <div class="checkbox">
                                    <label>
                                        <input type="checkbox" name="remember" {{ old('remember') ? 'checked' : '' }}> {{ __('Remember Me') }}
                                    </label>
                                </div>
                            </div>
                        </div>

                <div class="form-group row mb-0">
                            <div class="col-md-8 offset-md-4">
                                <button type="submit" class="btn btn-dark">
                                    {{ __('Login') }}
                                </button>

                                <a class="btn btn-link" href=" #">
                                    {{ __('Forgot Your Password?') }}
                                </a>
                            </div>
                        </div>
              </form>
            </div>
          </div>
        </div>
      </div>
    </div>
@endsection

resources/views/profile.blade.php
@extends('layouts.main')
@section('sidebar')
  <div class="col-md-8">
 @foreach($user_post as $key => $value)
    <div class=" d-flex justify-content-between" style="margin-bottom: 10px;">
      <h2>{{$value->users->name}} posts</h2>
      @if(Auth::user()->id == $user->id)
      <a class="btn btn-primary" href="{{route('posts.create')}}">Create New Post</a>
      @endif
    </div>
        <!-- Blog Post -->
        <div class="card mb-4" id="accordion">
          <img class="card-img-top" data-toggle="modal" data-target="#exampleModal" src="http://placehold.it/750x300" alt="Card image cap">
          <div class="modal fade" id="exampleModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
            <div class="modal-dialog modal-lg" role="document">
              <div class="modal-content">
                <div class="modal-body justify-content-center">
                  <img src="http://placehold.it/750x300" alt="Card image cap">
                </div>
                <div class="modal-footer">
                  <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
                </div>
              </div>
            </div>
          </div>
          <div class="card-header" id="heading{{$value->id}}">
            <a data-toggle="collapse" aria-expanded="false" aria-controls="collapse{{$value->id}}" href="#collapse{{$value->id}}" role="button"><h2>{{$value->title}}</h2>
            </a>
          </div>
          <div class="card-body" id="collapse{{$value->id}}" class="collapse">
            <p>{!!str_limit($value->content, $limit = 200, $end = '...')!!}</p>
              @if(Auth::user()->id == $value->users->id)
              <a href="{{route('posts.show',['slug'=>str_slug($value->title,'-'), 'id'=>$value->id])}}" class="btn btn-primary" style="margin-right: 5px;">Read More</a>
              <a href="{{route('posts.edit', ['id' => $value->id])}}" class="btn btn-primary" style="margin-right: 5px;">Edit</a>
              <a href="#" class="btn btn-primary">Delete</a>
              
              @else
              <a href="{{route('posts.show',['slug'=>str_slug($value->title,'-'), 'id'=>$value->id])}}" class="btn btn-primary" style="margin-right: 5px;">Read More</a>
              @endif
          </div>
          <div class="card-footer text-muted">
            Posted on {{$value->created_at}} by
            <a href="{{route('users.show',['id'=>$value->users->id])}}">{{$value->users->name}}</a>
          </div>
        </div>
    @endforeach
  </div>
  <!-- Sidebar Widgets Column -->

    <div class="col-md-4">
      <!-- Categories Widget -->
      <div class="card my-4" id="accordion">
        <div class="media mb-4" data-toggle="popover" title="{{$user->name}}" data-content="{{str_limit($user->email, 17, "...")}}"  style="margin-top: 20px; margin-left: 20px;">
            <img class="d-flex mr-3 rounded-circle" src="http://placehold.it/100x100" alt="">
            <div class="media-body" style="margin-left: 10px;">
              <h3>{{$user->name}}</h3>
              <h5>{{str_limit($user->email, 17, "...")}}</h5>
          </div>
        </div>
      </div>

      <!-- Side Widget -->
      <div class="card my-4">
        <h5 class="card-header">Side Widget</h5>
        <div class="card-body">
          <a class="btn btn-primary" href="{{route('posts.create')}}">New Post</a>
        </div>
      </div>
    </div>
@endsection

resources/views/register.blade.php
@extends('layouts.main')

@section('sidebar')
<div class="container main">
    <div class="row justify-content-center">
        <div class="col-md-8">
            <div class="card">
                <div class="card-header bg-dark box-shadow text-light"><strong><i>{{ __('User Register') }}</i></strong></div>

                <div class="card-body">
                    <form method="POST" action="{{ route('register') }}">
                        @csrf

                        @include('layouts.errors')
                        <div class="form-group row">
                            <label for="name" class="col-md-4 col-form-label text-md-right">{{ __('Name') }}</label>

                            <div class="col-md-6">
                                <input id="name" type="text" class="form-control{{ $errors->has('name') ? ' is-invalid' : '' }}" name="name" value="{{ old('name') }}" required autofocus>

                            </div>
                        </div>

                        <div class="form-group row">
                            <label for="email" class="col-md-4 col-form-label text-md-right">{{ __('E-Mail Address') }}</label>

                            <div class="col-md-6">
                                <input id="email" type="email" class="form-control{{ $errors->has('email') ? ' is-invalid' : '' }}" name="email" value="{{ old('email') }}" required>

                            </div>
                        </div>

                        <div class="form-group row">
                            <label for="password" class="col-md-4 col-form-label text-md-right">{{ __('Password') }}</label>

                            <div class="col-md-6">
                                <input id="password" type="password" class="form-control{{ $errors->has('password') ? ' is-invalid' : '' }}" name="password" required>

                            </div>
                        </div>

                        <div class="form-group row">
                            <label for="password-confirm" class="col-md-4 col-form-label text-md-right">{{ __('Confirm Password') }}</label>

                            <div class="col-md-6">
                                <input id="password-confirm" type="password" class="form-control" name="password_confirmation" required>
                            </div>
                        </div>

                        <div class="form-group row mb-0">
                            <div class="col-md-6 offset-md-4">
                                <button type="submit" class="btn btn-dark">
                                    {{ __('Register') }}
                                </button>
                            </div>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>
@endsection

resources/views/view_member.blade.php
@extends('layouts.main')
@section('title', 'Profile')
@section('topic','Member')
@section('sidebar')
  <div class="container main">
    <div class="row justify-content-center">
    @foreach($data as $key => $value)
    <div class="col-md-8">
      <div class="card mb-4">
        <div class="card-body">
          <div class="image"><img src="..\{{$value->img}}">
          </div> 
          <div class="text">
            Name: {{$value->name}}
            </br>
            Nickname: {{$value->nickname}}
            </br>
            Email: {{$value->email}}
            </br>
            Date of birth: {{date('d-m-Y', strtotime($value->date_of_birth))}}
          </div>
        </div>
      </div>
    </div>
    @endforeach
  </div>
</div>
@endsection